steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcx-trading-platform', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mcx-trading-platform']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'mcx-trading-platform'
    - '--image'
    - 'gcr.io/$PROJECT_ID/mcx-trading-platform'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'

images:
  - 'gcr.io/$PROJECT_ID/mcx-trading-platform'